mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("training/", include("training.urls")),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views
app_name = "users"
urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("profile/", views.ProfileUser.as_view(), name='profile'),
    path("password-change/", views.UserPasswordChange.as_view(), name="password_change"),
    path("password-change/done/", PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name="password_reset_confirm"),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete')

]

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link type="text/css" href="{% static 'training/css/main.css'%}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark nav-my-settings  ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">ELLA</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
          {% for option in menu_list %}
        <li class="nav-item">
            {%if option.content != "Настройки" %}
          <a class="nav-link {%if title == option.content %} active {% endif %} "  href="{% url option.ref  %}">
              {{option.content}}</a>
            {% else %}
            <a class="nav-link"  href="#" data-bs-toggle="modal" data-bs-target="#modal-settings">
              {{option.content}}</a>
            {% endif %}
        </li>
          {% endfor %}
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " data-bs-toggle="dropdown"  href="#">
                  <div class="div-user">
                      {% if user.is_authenticated %} {{user.username}}{% else %}Вход{% endif %}
                  </div></a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'users:logout'  %}">Вход в аккаунт</a></li>
                    <li><a class="dropdown-item" href="{% url 'users:register'  %}">Регистрация</a></li>
              </ul>
            </li>
      </ul>
    </div>
  </div>
</nav>


{% block content %} {% endblock %}

<!-- Modal -->
<div class="modal fade" id="modal-settings" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog ">
    <div class="modal-content">
      <div class="modal-header modal-header-my-background" data-bs-theme="dark">
        <h1 class="modal-title fs-5 " id="staticBackdropLabel">Настройки</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal"  aria-label="Close"></button>
      </div>
      <div class="modal-body">
          <div class="div-settings-option modal-background">
              <a class="ref-btn" href="{% url 'users:profile'  %}">Изменить данные пользователя</a>
              <a class="ref-btn" href="{% url 'users:password_change'  %}">Изменить пароль</a>
          </div>
      </div>
    </div>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/472fd7abb9.js" crossorigin="anonymous"></script>
<script src="{% static 'training/js/manage_textarea.js'%}"></script>
<script src="{% static 'training/js/validation.js'%}"></script>
</body>
</html>