mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("training/", include("training.urls")),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/training/urls.py
from django.urls import path

from . import views
app_name = "training"
urlpatterns = [
    path("", views.training_session, name="training_session"),
    path("statistic", views.statistic, name="statistic"),

    path("training_session/<str:training_mode>/<str:difficulty_level>/", views.display_test, name="display_test"),
    path("training_session/<str:training_mode>/<str:difficulty_level>/<int:exercise_num>", views.display_exercise,
         name="display_exercise"),
    path('training_session/<str:training_mode>/<str:difficulty_level>/<int:exercise_num>/grade/',
         views.exercise_grade, name='exercise_grade'),
    path('training_session/<str:training_mode>/<str:difficulty_level>/results', views.results,
         name='results'),
]

mysite/users/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views
app_name = "users"
urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("profile/", views.ProfileUser.as_view(), name='profile'),
    path("password-change/", views.UserPasswordChange.as_view(), name="password_change"),
    path("password-change/done/", PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name="password_reset_confirm"),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete')

]

mysite/training/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F
from django.http import HttpResponse
from django.urls import reverse_lazy

from .models import Statistic, Difficulty_level, Choice, Result, Training_mode
from django.shortcuts import render, redirect, get_object_or_404

menu_list = [
    {'ref': 'training:training_session', 'content': 'Выбор режима'},
    {'ref': 'training:statistic', 'content': 'Статистика пользователя'},
    {'ref': 'training:settings', 'content': 'Настройки'}
]

value_diff_list = {
    '1': 'easy-translate',
    '2': 'medium-translate',
    '3': 'hard-translate',
    '4': 'easy-sound',
    '5': 'medium-sound',
    '6': 'hard-sound',
}


def get_grade(count, correct_count, difficulty_level):
    percentage = correct_count / count * 100
    grade_thresholds = {
        "easy": [(90, 5, "greate-grade"), (70, 4, "good-grade"), (50, 3, "ok-grade")],
        "medium": [(80, 5, "greate-grade"), (60, 4, "good-grade"), (40, 3, "ok-grade")],
        "hard": [(70, 5, "greate-grade"), (50, 4, "good-grade"), (30, 3, "ok-grade")]
    }

    for threshold, grade, grade_style in grade_thresholds[difficulty_level.split("-")[0]]:
        if percentage >= threshold:
            return grade, grade_style

    return 2, "bad-grade"


@login_required
def statistic(request):
    statistic_of_user = request.user.statistic
    statistic_exist = statistic_of_user is not None
    average_translate, average_sound, common_average, translate_count, sound_count, common_count = None, None, None, None, None, None
    if statistic_exist:
        average_translate = round(statistic_of_user.calc_average_grade_by_translate(), 2)
        average_sound = round(statistic_of_user.calc_average_grade_by_sound(), 2)
        common_average = round(statistic_of_user.calc_average_grade(), 2)
        translate_count = statistic_of_user.translate_grades.count()
        sound_count = statistic_of_user.sound_grades.count()
        common_count = sound_count + translate_count
    data = {'title': 'Статистика пользователя',
            'statistic_exist': statistic_exist,
            'average_translate': average_translate,
            'average_sound': average_sound,
            'common_average': common_average,
            'translate_count': translate_count,
            'sound_count': sound_count,
            'common_count': common_count,
            'menu_list': menu_list,
            }
    return render(request, "training/statistic.html", context=data)


@login_required
def training_session(request):
    if request.method == "POST":
        typeOfTraining = request.POST['TypeOfTraining']
        if typeOfTraining == "translate" or typeOfTraining == "sound":
            difficulty_level = value_diff_list[request.POST[f'diff_option_{typeOfTraining}']]
            return redirect(reverse_lazy('training:display_test',
                                         kwargs={'training_mode': typeOfTraining,
                                                 'difficulty_level': difficulty_level}))
    data = {
        'title': "Выбор режима",
        'menu_list': menu_list,
    }
    return render(request, "training/training_session.html", context=data)


@login_required
def display_test(request, training_mode, difficulty_level):
    request.user.clean_data()
    difficulty_level_bd = get_object_or_404(Difficulty_level, name=difficulty_level)
    difficulty_level_bd.deactivate_all_blocks()
    exercise_block = difficulty_level_bd.get_random_exercise_block()
    exercise_block.set_nums()
    if request.user.statistic is None:
        request.user.create_statistic()
    results_new = Result.objects.create(user=request.user,
                                        training_mode=(
                                            get_object_or_404(Training_mode, name=training_mode)))
    results_new.save()
    return redirect(reverse_lazy('training:display_exercise',
                                 kwargs={'training_mode': training_mode,
                                         'difficulty_level': difficulty_level,
                                         'exercise_num': 0}))


@login_required
def display_exercise(request, training_mode, difficulty_level, exercise_num):
    difficulty_level_bd = get_object_or_404(Difficulty_level, name=difficulty_level)
    exercise_block = difficulty_level_bd.exercise_block_set.filter(is_active_block=True)[0]
    exercises = exercise_block.exercise_set.order_by('num')
    current_exercise, next_exercise, prev_exercise = None, None, None
    current_exercise = exercises[exercise_num]
    if exercise_num != len(exercises) - 1:
        next_exercise = exercises[exercise_num + 1]
    if exercise_num != 0:
        prev_exercise = exercises[exercise_num - 1]

    users_answer = request.user.is_answered_check(current_exercise)

    context = {'training_mode': training_mode,
               'difficulty_level': difficulty_level,
               'exercise': current_exercise,
               'next_exercise': next_exercise,
               'prev_exercise': prev_exercise,
               'users_answer': users_answer,
               'title': "Вопрос №" + str(exercise_num + 1),
               'menu_list': menu_list,
               }
    return render(request,
                  'training/display_exercise.html', context)


@login_required
def exercise_grade(request, training_mode, difficulty_level, exercise_num):
    difficulty_level_bd = get_object_or_404(Difficulty_level, name=difficulty_level)
    exercise_block = difficulty_level_bd.exercise_block_set.filter(is_active_block=True)[0]
    exercises = exercise_block.exercise_set.order_by('num')
    exercise = exercises[exercise_num]
    if not request.user.is_answered_check(exercise) and request.method == "POST":
        correct_answers = exercise.get_correct_answers().values_list('answer', flat=True)
        user_answer = request.POST['answer']
        user_answer = " ".join(user_answer.split())
        choice = Choice(user=request.user,
                        exercise=exercise, user_answer=user_answer)
        choice.save()
        correct_answers = [answer.lower() for answer in correct_answers]

        is_correct = user_answer.lower() in correct_answers
        result = Result.objects.get(user=request.user,
                                    training_mode=(
                                        get_object_or_404(Training_mode, name=training_mode)))
        if is_correct is True:
            result.correct = F('correct') + 1
        else:
            result.wrong = F('wrong') + 1
        result.save()

    if exercise_num != len(exercises) - 1:
        return redirect(reverse_lazy('training:display_exercise',
                                     kwargs={'training_mode': training_mode,
                                             'difficulty_level': difficulty_level,
                                             'exercise_num': exercise_num + 1}))
    else:
        skipped_exercises_count = request.user.get_skipped_exercise_count(exercises)
        context = {'training_mode': training_mode,
                   'difficulty_level': difficulty_level,
                   'first_exercise_num': 0,
                   'skipped_exercises_count': skipped_exercises_count,
                   'title': "Переход к результатам",
                   'menu_list': menu_list}
        return render(request,
                      'training/before_result.html', context)


@login_required
def results(request, training_mode, difficulty_level):
    difficulty_level_bd = get_object_or_404(Difficulty_level, name=difficulty_level)
    exercise_block = difficulty_level_bd.exercise_block_set.filter(is_active_block=True)[0]
    exercise_block.active_off()
    exercises = exercise_block.exercise_set.order_by('num')
    results_of_test = Result.objects.filter(user=request.user,
                                            training_mode=(
                                                get_object_or_404(Training_mode, name=training_mode)))[0]

    correct, wrong, skipped = 0, 0, 10
    correct = results_of_test.correct if results_of_test.correct > 0 else 0
    wrong = results_of_test.wrong if results_of_test.wrong > 0 else 0
    skipped = len(exercises) - (correct + wrong)
    grade, grade_style = get_grade(len(exercises), correct, difficulty_level)
    if not results_of_test.processed:
        stat = request.user.statistic
        stat.add_grade(grade, training_mode)
        results_of_test.end_of_processing()
    result_data = {'correct': correct, 'wrong': wrong, 'skipped': skipped, 'number': len(exercises), 'grade': grade}
    for exercise in exercises:
        if request.user.is_answered_check(exercise) is None:
            choice = Choice(user=request.user,
                            exercise=exercise, user_answer="")
            choice.save()
    wrong_answers, wrong_exercises, correct_answers = [], [], []
    for exercise in exercises:
        if request.user.get_answer_if_choice_wrong(exercise) is not None:
            wrong_answers.append(request.user.get_answer_if_choice_wrong(exercise))
            wrong_exercises.append(exercise)
            correct_answers.append(exercise.get_correct_answers().first())
    wrong_data = [{'wrong_answers': t[0], 'wrong_exercises': t[1], 'correct_answers': t[2]} for t in zip(wrong_answers,
                                                                                                         wrong_exercises,
                                                                                                         correct_answers)]
    context = {'training_mode': training_mode,
               'difficulty_level': difficulty_level,
               'title': "Результаты",
               'result_data': result_data,
               'wrong_data': wrong_data,
               'menu_list': menu_list,
               'grade_style': grade_style}
    return render(request,
                  'training/results.html', context)

mysite/training/templates/training/before_result.html
{% extends 'base.html' %}
{% block content %}

<div class="exercise-container">
    <div class="exercise-css">
        <h1>{{title}}</h1>
        <div>
            <p>Пропущенных заданий: <strong>{{skipped_exercises_count}}</strong></p>
        </div>
          <div class="refs-before-results">
              <div>
              <a class="ref-btn-ex ref-animatic-btn-nav ref-before-results" href="{% url 'training:display_exercise' training_mode difficulty_level first_exercise_num %}">Вернуться к тесту</a>
          </div>
          <div>
              <a class="ref-btn-ex ref-animatic-btn-res ref-before-results" href="{% url 'training:results' training_mode difficulty_level  %}">Перейти к результатам</a>
          </div>
          </div>
    </div>
</div>
{% endblock %}

mysite/training/templates/training/display_exercise.html
{% extends 'base.html' %}
{% block content %}
<div class="exercise-container">
    <div class="exercise-css">
        <h1>{{title}}</h1>
        <form id="exercise-form"
                action="{% url 'training:exercise_grade' training_mode difficulty_level exercise.num %}"
                method="post">
              {% csrf_token %}
                  <div class="task-css">
                      <label class="text-task-base" for="task_field">{%if training_mode == "translate"%}Выполните перевод текста на Английский язык:
                      {%else%}
                      Прослушайте сообщение и напишите услышанное:{%endif%} </label>
                      {%if training_mode == "translate"%}
                      <div class="text-task-css" id="task_field">{{ exercise.task }}</div>
                      {%else%}
                      <audio class="audio-task-css" id="task_field" controls src="{{ exercise.audio_task.url }}"></audio>
                      {%endif%}
                  </div>
                  <div class="answer-field-cont">
                      <textarea class="form-control textarea-max-height" name="answer" id="answer_field" rows="7"{% if users_answer != None %} readonly {%endif %} placeholder="Поле для ответа">
                          {% if users_answer != None %} {{users_answer}} {%endif %}
                      </textarea>
                  </div>
              <div class="text-center">
                  <input type="submit" class="btn-default{% if users_answer != None %} btn-disabled"  disabled {% else %} " {%endif %}
                         value="Ответить"/>
              </div>
          </form>
        <div class="exercise-refs">
      {% if next_exercise %}
          <div>
              <a class="ref-btn-ex ref-animatic-btn-nav" href="{% url 'training:display_exercise' training_mode difficulty_level next_exercise.num %}">Следующее задание</a>
          </div>
        {%else %}
        <div>
              <a class="ref-btn-ex ref-animatic-btn-res" href="{% url 'training:exercise_grade' training_mode difficulty_level exercise.num %}">К результатам</a>
          </div>
      {% endif %}
      {% if prev_exercise %}
          <div>
              <a class="ref-btn-ex ref-animatic-btn-nav" href="{% url 'training:display_exercise' training_mode difficulty_level prev_exercise.num %}">Прошлое задание</a>
          </div>
      {% endif %}
    </div>
    </div>
</div>

{% endblock %}

mysite/training/templates/training/results.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div>
        <table class="table table-results">
            <thead class="table-header-css">
                <tr class="table-header-tr-css">
                    <th scope="col" >Показатели</th>
                    <th scope="col" >Результаты</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Всего вопросов в тесте</td>
                    <td>{{ result_data.number }}</td>
                </tr>
                <tr>
                    <td>Правильные ответы</td>
                    <td>{{ result_data.correct }}</td>
                </tr>
                <tr>
                    <td>Неправильные ответы</td>
                    <td>{{ result_data.wrong }}</td>
                </tr>
                <tr>
                    <td>Пропущено вопросов</td>
                    <td>{{ result_data.skipped }}</td>
                </tr>
                <tr>
                    <td>Оценка</td>
                    <td class="{{grade_style}} grade-font">{{ result_data.grade }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% if result_data.correct < result_data.number %}
    <h2 class="wrong-h2">Неправильные ответы:</h2>
    {% endif %}
    <div class="wrong-container">
        {% for wrong in wrong_data %}

            <div class="wrong-answers-css {% if forloop.counter|divisibleby:'2' %} wrong-answers-right {% else %} wrong-answers-left {% endif %}">
                <div class="answer-set-border-bottom">
                    <div class="answer-set">
                    {%if training_mode == "translate"%}
                    <span class="text-task-base">Перевести текст:</span>
                    <div class="text-task-css answer-css task-for-wrong"> {{wrong.wrong_exercises.task}}</div>
                    {% else %}
                    <span class="text-task-base">Прослушать аудио и написать услышанное:</span>
                    <audio class="audio-task-css wrong-audio" controls src="{{ wrong.wrong_exercises.audio_task.url }}"></audio>
                    {% endif %}
                </div>
                </div>
                <div class="answer-set-border-bottom">
                    <div class="answer-set">
                    <span class="text-task-base">Ответ пользователя: </span>
                    <span class="text-task-css answer-css wrong-answer">{{wrong.wrong_answers}}</span>
                </div>
                </div>
               <div class="answer-set">
                    <span class="text-task-base">Правильный ответ: </span>
                    <span class="text-task-css answer-css correct-answer" >{{wrong.correct_answers}}</span>
                </div>


            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mysite/training/templates/training/statistic.html
{% extends 'base.html' %}
{% block content %}
{% if statistic_exist %}
    <div class="statistic-div">
        <table class="table">
            <tbody>
                <tr>
                    <td >Кол-во пройденных тестов в режиме "Перевод"</td>
                    <td>{{ translate_count }}</td>
                </tr>
                <tr>
                    <td>Средний балл в режиме "Перевод"</td>
                    <td>{{ average_translate }}</td>
                </tr>
                <tr>
                    <td>Кол-во пройденных тестов в режиме "Звучание"</td>
                    <td>{{ sound_count }}</td>
                </tr>
                <tr>
                    <td>Средний балл в режиме "Звучание"</td>
                    <td>{{ average_sound }}</td>
                </tr>
                <tr>
                    <td>Всего тестов пройдено</td>
                    <td>{{ common_count }}</td>
                </tr>
                <tr>
                    <td>Общий средний балл</td>
                    <td>{{ common_average }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% else %}
        <p>Вы еще не приступали к обучению</p>
    {% endif %}
{% endblock %}

mysite/training/templates/training/training_session.html
{% extends 'base.html' %}
{% block content %}



<div class="form-container">
    <div class="training-mode-div">
        <form method="post" class="training-mode-form">
        {% csrf_token %}
        <input  type="hidden" name="TypeOfTraining" value="translate">
        <div class="form-training-mode-header"><h2>Режим "Перевод"</h2></div>
        <div class="form-training-mode-body"><label class="form-label" for="dif_sel_id_translate">Уровень сложности:</label>
            <select id="dif_sel_id_translate" class="form-select" name="diff_option_translate" size="1">
                <option value="1">Легкий</option>
                <option value="2">Средний</option>
                <option value="3">Сложный</option>
            </select>
        </div>
            <p><button type="submit" class="btn-training-mode">Перейти к тесту</button> </p>
    </form>
    </div>
    <div class="training-mode-div">
        <form method="post" class="training-mode-form">
                    {% csrf_token %}
                    <input  type="hidden" name="TypeOfTraining" value="sound">
                    <div class="form-training-mode-header"><h2>Режим "Звучание"</h2></div>
                    <div class="form-training-mode-body"><label class="form-label" for="dif_sel_id_sound">Уровень сложности:</label>
                        <select class="form-select" id="dif_sel_id_sound" name="diff_option_sound" size="1">
                            <option value="4">Легкий</option>
                            <option value="5">Средний</option>
                            <option value="6">Сложный</option>
                        </select>
                    </div>

                    <p><button type="submit" class=" btn-training-mode">Перейти к тесту</button> </p>
                </form>
    </div>

</div>
{% endblock %}

mysite/training/templates/training/translate_results.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>{{title}}</h1>
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" >Показатели</th>
                    <th scope="col" >Результаты</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Всего вопросов в тесте</td>
                    <td>{{ number }}</td>
                </tr>
                <tr>
                    <td>Правильные ответы</td>
                    <td>{{ correct }}</td>
                </tr>
                <tr>
                    <td>Неправильные ответы</td>
                    <td>{{ wrong }}</td>
                </tr>
                <tr>
                    <td>Пропущено вопросов</td>
                    <td>{{ skipped }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div>
        {% for wrong in wrong_data %}
            <div>
                <p>Задание:Перевести текст "{{wrong.wrong_exercises.task}}"</p>
                <p>Ответ пользователя: {{wrong.wrong_answers}}</p>
                <p>Правильный ответ: {{wrong.correct_answers}}</p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}