mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

urlpatterns = [
    path("training/", include("training.urls")),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/training/urls.py
from django.urls import path

from . import views
app_name = "training"
urlpatterns = [
    path("", views.training_session, name="training_session"),
    path("statistic", views.statistic, name="statistic"),

    path("training_session/<str:training_mode>/<str:difficulty_level>/", views.display_test, name="display_test"),
    path("training_session/<str:training_mode>/<str:difficulty_level>/<int:exercise_num>", views.display_exercise,
         name="display_exercise"),
    path('training_session/<str:training_mode>/<str:difficulty_level>/<int:exercise_num>/grade/',
         views.exercise_grade, name='exercise_grade'),
    path('training_session/<str:training_mode>/<str:difficulty_level>/results', views.results,
         name='results'),
]

mysite/users/urls.py
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views
app_name = "users"
urlpatterns = [
    path("login/", views.LoginUser.as_view(), name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("register/", views.RegisterUser.as_view(), name="register"),
    path("profile/", views.ProfileUser.as_view(), name='profile'),
    path("password-change/", views.UserPasswordChange.as_view(), name="password_change"),
    path("password-change/done/", PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
    path('password-reset/',
         PasswordResetView.as_view(template_name="users/password_reset_form.html",
                                   email_template_name="users/password_reset_email.html",
                                   success_url=reverse_lazy("users:password_reset_done")),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name="password_reset_confirm"),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete')

]

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин",
                               widget=forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                             'placeholder': 'Логин'}))
    password = forms.CharField(label="Пароль",
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': True,
                                                                 'placeholder': 'Пароль'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Логин",
                               widget=forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                             'placeholder': 'Логин'}))
    password1 = forms.CharField(label="Пароль",
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control password-new', 'required': True,
                                           'placeholder': 'Пароль'}))
    password2 = forms.CharField(label="Повтор пароля",
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control password-repeat', 'required': True,
                                           'placeholder': 'Повтор пароля'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': 'Эл. почта',
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                            'placeholder': 'Эл. почта'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                'placeholder': 'Фамилия'})
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Данная эл. почта уже есть в системе!")
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label="Логин", widget=forms.TextInput(attrs={'class': 'form-control',
                                                                                           'required': True,
                                                                                           'placeholder': 'Логин'}))
    email = forms.CharField(disabled=True, label="Эл. почта",
                            widget=forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                          'placeholder': 'Эл. почта'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия'
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                 'placeholder': 'Имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'required': True,
                                                'placeholder': 'Фамилия'})
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                                            'required': True,
                                                                                            'placeholder': 'Старый пароль'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': True,
                                                                      'placeholder': 'Новый пароль'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-control', 'required': True,
                                                                      'placeholder': 'Подтверждение пароля'}))

mysite/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView

from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm

menu_list = [
    {'ref': 'training:training_session', 'content': 'Выбор режима'},
    {'ref': 'training:statistic', 'content': 'Статистика пользователя'},
    {'ref': 'training:settings', 'content': 'Настройки'}
]


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {"title": 'Авторизация'}

    # def get_success_url(self):
    #     return reverse_lazy('training:menu')


# def login_user(request):
#     error_auth_msg = ""
#     if request.method == 'POST':
#         form = LoginUserForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'],
#                                 password=cd['password'])
#             if user and user.is_active:
#                 login(request, user)
#                 return HttpResponseRedirect(reverse_lazy('training:menu'))
#             else:
#                 error_auth_msg = "Неправильный логин или пароль"
#     else:
#         form = LoginUserForm()
#     return render(request, 'users/login.html', {'form': form, 'error_auth_msg': error_auth_msg, 'is_users_app': True})
#
#
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse_lazy('users:login'))


#
# def register(request):
#     if request.method == 'POST':
#         form = RegisterUserForm(request.POST)
#         if form.is_valid():
#             user = form.save(commit=False)
#             user.set_password(form.cleaned_data['password'])
#             user.save()
#             return HttpResponseRedirect(reverse_lazy('users:login'))
#     else:
#         form = RegisterUserForm()
#     return render(request, 'users/register.html', {'form': form})


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = "users/profile.html"
    extra_context = {
        'title': 'Изменение профиля',
        'menu_list': menu_list,
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(LoginRequiredMixin, PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': 'Изменение пароля',
                     'menu_list': menu_list}

mysite/users/templates/users/Password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<div class="form-users-container">
   <div class="form-users-css">
      <h1>Сброс пароля</h1>
       <p class="reset-text">{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
       <p class="reset-text">{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
   </div>
</div>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}


<div class="form-users-container">
   <div class="form-users-css">
      <h1 class="form-users-title">{{title}}</h1>
      <form method="post" class="needs-validation form-users-inputs" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>
         {% for f in form %}
         <div class="form-obj-set">
            <div class="form-obj-field">{{f}}</div>
           <div class="form-error">
               {{f.errors}}
           </div>
         </div>
         {% endfor %}
         <div class="form-error">{{ form.non_field_errors}}</div>
         <p><button class="btn-default btn-users" type="submit">Войти</button></p>
      </form>
      <div class="form-users-refs">
         <div class="ref-users-left">
              <a class="ref-btn-users ref-animatic-btn-users" href="{% url 'users:register'  %}">Регистрация</a>
          </div>
         <div class="ref-users-right">
              <a class="ref-btn-users ref-animatic-btn-users" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
          </div>
      </div>
   </div>
</div>

{% endblock %}

mysite/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<div class="form-users-container form-pass-change-done-size">
   <div class="form-users-css form-pass-change-done-size">
       <div class="title-profile">
           <h1>Пароль успешно изменен!</h1>
       </div>
       <div class="form-users-refs ref-position-profile">
          <a class="ref-btn-users ref-animatic-btn-users" href="{% url 'training:training_session'%}">Вернуться в главное окно</a>
      </div>
       </div>
</div>

{% endblock %}

mysite/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<div class="form-users-container">
   <div class="form-users-css">
      <div class="title-profile">
          <h1>{{title}}</h1>
      </div>
       <div class="inside-password-change-container">
            <form method="post" class="needs-validation form-users-inputs" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>

         {% for f in form %}

         <div class="form-obj-set">
           <div class="form-obj-field">{{f}}</div>
           <div class="form-error change-pass-errors">
               {{f.errors}}
           </div>
         </div>

         {% endfor %}
         <div class="form-error">{{ form.non_field_errors}}</div>
         <button class="btn-default btn-users" type="submit">Сохранить</button>
      </form>
       </div>
      <div class="form-users-refs ref-position-profile">
          <a class="ref-btn-users ref-animatic-btn-users" href="{% url 'users:profile' %}">Перейти к изменению профиля</a>
      </div>
   </div>
</div>

{% endblock %}

mysite/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

<div class="form-users-container">
   <div class="form-users-css">
      <h1>Пароль изменен</h1>
       <div class="text">
           <p class="reset-text">Ваш пароль успешно изменен. Используйте новый пароль для <a href="{% url 'users:login' %}">входа в систему</a>.</p>
       </div>
       </div>
</div>
{% endblock %}

mysite/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}

<div class="form-users-container">
   <div class="form-users-css">
      <h1>Новый пароль</h1>
      <form method="post" class="needs-validation form-users-inputs form-new-pass" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>
         {% for f in form %}
         <div class="form-obj-set">
            <div class="form-obj-field">{{f}}</div>
           <div class="form-error">
               {{f.errors}}
           </div>
         </div>
         {% endfor %}
         <div  class="form-error">{{ form.non_field_errors}}</div>
         <p><button id="new-pass-btn" class="btn-default btn-users" type="submit">Сохранить</button></p>
      </form>
   </div>
</div>

{% endblock %}

mysite/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
{% endautoescape %}

mysite/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div class="form-users-container">
   <div class="form-users-css form-email-reset">
      <h1>Восстановление</h1>
      <form method="post" class="needs-validation form-users-inputs" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>
         {% for f in form %}
             <div id="input-set-email" class="input-group has-validation email-input">
                <span class="input-group-text" id="validationTooltipUsernamePrepend">@</span>
                {{f}}
             </div>
          <div class="form-error">
               {{f.errors}}
           </div>
         {% endfor %}
         <div class="form-error">{{ form.non_field_errors}}</div>
         <p><button id="reset-btn" class="btn-default btn-users" type="submit">Сбросить пароль</button></p>
      </form>
   </div>
</div>


{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="form-users-container">
   <div class="form-users-css">
      <div class="title-profile">
          <h1>{{title}}</h1>
      </div>
       <div class="inside-profile-container">
      <form method="post" class="needs-validation form-users-inputs" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>

         {% for f in form %}

         <div class="form-obj-set profile-set">
            <label class="form-label profile-label" for="{{f.id_for_label}}">{{f.label}}: </label>
            <div class="form-obj-field">{{f}}</div>
           <div class="form-error">
               {{f.errors}}
           </div>
         </div>

         {% endfor %}
         <div class="form-error">{{ form.non_field_errors}}</div>
         <button class="btn-default btn-users" type="submit">Сохранить</button>
      </form>
           </div>
      <div class="form-users-refs ref-position-profile">
          <a class="ref-btn-users ref-animatic-btn-users" href="{% url 'users:password_change' %}">Перейти к изменению пароля</a>
      </div>
   </div>
</div>

{% endblock %}

mysite/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<div class="form-users-container">
   <div class="form-users-css reg-form-size">
      <h1 class="form-users-title">{{title}}</h1>
      <form method="post" class="needs-validation form-users-inputs" novalidate>
         {% csrf_token %}
         <input type="hidden" name="next" value="{{ next }}"/>
         {% for f in form %}
         {% if f.label != "Пароль" and f.label != "Повтор пароля" %}
         <div class="form-obj-set">
             {% if f.label != "Эл. почта" %}
            <div class="form-obj-field">{{f}}</div>
             {% else %}
             <div class="input-group has-validation">
                <span class="input-group-text" id="validationTooltipUsernamePrepend">@</span>
                {{f}}
             </div>
             {% endif %}
           <div class="form-error">
               {{f.errors}}
           </div>
         </div>
          {% endif %}
         {% endfor %}
          <div class="password-set">
              <div class="passwords">
              {% for f in form %}
                {% if f.label == "Пароль" or f.label == "Повтор пароля" %}
                 <div>
                    <div class="form-obj-field">{{f}}</div>
                 </div>
                {% endif %}
                {% if forloop.last %}
              </div>
                  <div class="form-error">
                    {{f.errors}}
                  </div>
                {% endif %}
              {% endfor %}

          </div>

         <div class="form-error">{{ form.non_field_errors}}</div>
         <p><button class="btn-default btn-users" type="submit">Регистрация</button></p>
      </form>
   </div>
</div>

{% endblock %}